# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'appMainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(780, 617)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setToolTipDuration(2)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.view_DMDMaskImage = QtWidgets.QGraphicsView(self.centralwidget)
        self.view_DMDMaskImage.setGeometry(QtCore.QRect(20, 290, 480, 270))
        self.view_DMDMaskImage.setObjectName("view_DMDMaskImage")
        self.tab_MaskFunctionality = QtWidgets.QTabWidget(self.centralwidget)
        self.tab_MaskFunctionality.setGeometry(QtCore.QRect(510, 290, 241, 131))
        self.tab_MaskFunctionality.setObjectName("tab_MaskFunctionality")
        self.Calibration = QtWidgets.QWidget()
        self.Calibration.setObjectName("Calibration")
        self.txt_DMDCalibrationMaskRatio = QtWidgets.QPlainTextEdit(self.Calibration)
        self.txt_DMDCalibrationMaskRatio.setGeometry(QtCore.QRect(2, 12, 80, 21))
        self.txt_DMDCalibrationMaskRatio.setObjectName("txt_DMDCalibrationMaskRatio")
        self.label_DMDCalibrationMaskRatio = QtWidgets.QLabel(self.Calibration)
        self.label_DMDCalibrationMaskRatio.setGeometry(QtCore.QRect(92, 12, 141, 16))
        self.label_DMDCalibrationMaskRatio.setObjectName("label_DMDCalibrationMaskRatio")
        self.tab_MaskFunctionality.addTab(self.Calibration, "")
        self.Threshold = QtWidgets.QWidget()
        self.Threshold.setObjectName("Threshold")
        self.txt_ThresholdLevel = QtWidgets.QPlainTextEdit(self.Threshold)
        self.txt_ThresholdLevel.setGeometry(QtCore.QRect(0, 30, 104, 31))
        self.txt_ThresholdLevel.setObjectName("txt_ThresholdLevel")
        self.label_ThresholdLevel = QtWidgets.QLabel(self.Threshold)
        self.label_ThresholdLevel.setGeometry(QtCore.QRect(120, 30, 101, 20))
        self.label_ThresholdLevel.setObjectName("label_ThresholdLevel")
        self.tab_MaskFunctionality.addTab(self.Threshold, "")
        self.Slit = QtWidgets.QWidget()
        self.Slit.setObjectName("Slit")
        self.spinBox_NumberOfSlits = QtWidgets.QSpinBox(self.Slit)
        self.spinBox_NumberOfSlits.setGeometry(QtCore.QRect(20, 0, 48, 24))
        self.spinBox_NumberOfSlits.setMinimum(1)
        self.spinBox_NumberOfSlits.setMaximum(4)
        self.spinBox_NumberOfSlits.setObjectName("spinBox_NumberOfSlits")
        self.label_NumberOfSlits = QtWidgets.QLabel(self.Slit)
        self.label_NumberOfSlits.setGeometry(QtCore.QRect(80, 0, 101, 16))
        self.label_NumberOfSlits.setObjectName("label_NumberOfSlits")
        self.txt_SlitWidth = QtWidgets.QPlainTextEdit(self.Slit)
        self.txt_SlitWidth.setGeometry(QtCore.QRect(0, 30, 104, 31))
        self.txt_SlitWidth.setObjectName("txt_SlitWidth")
        self.txt_SlitSeparation = QtWidgets.QPlainTextEdit(self.Slit)
        self.txt_SlitSeparation.setGeometry(QtCore.QRect(0, 70, 104, 31))
        self.txt_SlitSeparation.setObjectName("txt_SlitSeparation")
        self.label_SlitWidth = QtWidgets.QLabel(self.Slit)
        self.label_SlitWidth.setGeometry(QtCore.QRect(120, 40, 91, 16))
        self.label_SlitWidth.setObjectName("label_SlitWidth")
        self.label_SlitSeparation = QtWidgets.QLabel(self.Slit)
        self.label_SlitSeparation.setGeometry(QtCore.QRect(110, 80, 121, 16))
        self.label_SlitSeparation.setObjectName("label_SlitSeparation")
        self.tab_MaskFunctionality.addTab(self.Slit, "")
        self.Pinhole = QtWidgets.QWidget()
        self.Pinhole.setObjectName("Pinhole")
        self.spinBox_NumberOfPinholes = QtWidgets.QSpinBox(self.Pinhole)
        self.spinBox_NumberOfPinholes.setGeometry(QtCore.QRect(20, 0, 48, 24))
        self.spinBox_NumberOfPinholes.setMinimum(1)
        self.spinBox_NumberOfPinholes.setMaximum(4)
        self.spinBox_NumberOfPinholes.setObjectName("spinBox_NumberOfPinholes")
        self.label_NumberOfPinholes = QtWidgets.QLabel(self.Pinhole)
        self.label_NumberOfPinholes.setGeometry(QtCore.QRect(80, 0, 121, 16))
        self.label_NumberOfPinholes.setObjectName("label_NumberOfPinholes")
        self.label_PinholeRadius = QtWidgets.QLabel(self.Pinhole)
        self.label_PinholeRadius.setGeometry(QtCore.QRect(110, 40, 121, 16))
        self.label_PinholeRadius.setObjectName("label_PinholeRadius")
        self.txt_PinholeRadius = QtWidgets.QPlainTextEdit(self.Pinhole)
        self.txt_PinholeRadius.setGeometry(QtCore.QRect(0, 30, 104, 31))
        self.txt_PinholeRadius.setObjectName("txt_PinholeRadius")
        self.txt_PinholePitch = QtWidgets.QPlainTextEdit(self.Pinhole)
        self.txt_PinholePitch.setGeometry(QtCore.QRect(0, 70, 104, 31))
        self.txt_PinholePitch.setObjectName("txt_PinholePitch")
        self.label_PinholePitch = QtWidgets.QLabel(self.Pinhole)
        self.label_PinholePitch.setGeometry(QtCore.QRect(120, 80, 111, 16))
        self.label_PinholePitch.setObjectName("label_PinholePitch")
        self.tab_MaskFunctionality.addTab(self.Pinhole, "")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(530, 430, 191, 131))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.txt_DMDSizeXMaskGen = QtWidgets.QPlainTextEdit(self.widget)
        self.txt_DMDSizeXMaskGen.setObjectName("txt_DMDSizeXMaskGen")
        self.horizontalLayout_6.addWidget(self.txt_DMDSizeXMaskGen)
        self.label_DMDSizeXMaskGen = QtWidgets.QLabel(self.widget)
        self.label_DMDSizeXMaskGen.setObjectName("label_DMDSizeXMaskGen")
        self.horizontalLayout_6.addWidget(self.label_DMDSizeXMaskGen)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.txt_DMDSizeYMaskGen = QtWidgets.QPlainTextEdit(self.widget)
        self.txt_DMDSizeYMaskGen.setObjectName("txt_DMDSizeYMaskGen")
        self.horizontalLayout_7.addWidget(self.txt_DMDSizeYMaskGen)
        self.label_DMDSizeYMaskGen = QtWidgets.QLabel(self.widget)
        self.label_DMDSizeYMaskGen.setObjectName("label_DMDSizeYMaskGen")
        self.horizontalLayout_7.addWidget(self.label_DMDSizeYMaskGen)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.btn_DMDMaskGen = QtWidgets.QPushButton(self.widget)
        self.btn_DMDMaskGen.setObjectName("btn_DMDMaskGen")
        self.verticalLayout_2.addWidget(self.btn_DMDMaskGen)
        self.btn_DMDMaskSave = QtWidgets.QPushButton(self.widget)
        self.btn_DMDMaskSave.setObjectName("btn_DMDMaskSave")
        self.verticalLayout_2.addWidget(self.btn_DMDMaskSave)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(-3, 259, 781, 31))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(16, 20, 751, 241))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.view_CameraImage = QtWidgets.QGraphicsView(self.splitter)
        self.view_CameraImage.setObjectName("view_CameraImage")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_CamImageImport = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_CamImageImport.setObjectName("btn_CamImageImport")
        self.verticalLayout.addWidget(self.btn_CamImageImport)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.txt_DMDSizeX = QtWidgets.QPlainTextEdit(self.layoutWidget)
        self.txt_DMDSizeX.setObjectName("txt_DMDSizeX")
        self.horizontalLayout_2.addWidget(self.txt_DMDSizeX)
        self.label_DMDSizeX = QtWidgets.QLabel(self.layoutWidget)
        self.label_DMDSizeX.setObjectName("label_DMDSizeX")
        self.horizontalLayout_2.addWidget(self.label_DMDSizeX)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.txt_DMDSizeY = QtWidgets.QPlainTextEdit(self.layoutWidget)
        self.txt_DMDSizeY.setObjectName("txt_DMDSizeY")
        self.horizontalLayout.addWidget(self.txt_DMDSizeY)
        self.label_DMDSizeY = QtWidgets.QLabel(self.layoutWidget)
        self.label_DMDSizeY.setObjectName("label_DMDSizeY")
        self.horizontalLayout.addWidget(self.label_DMDSizeY)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.txt_DMDCalibrationImageRatio = QtWidgets.QPlainTextEdit(self.layoutWidget)
        self.txt_DMDCalibrationImageRatio.setObjectName("txt_DMDCalibrationImageRatio")
        self.horizontalLayout_3.addWidget(self.txt_DMDCalibrationImageRatio)
        self.label_DMDCalibrationImageRatio = QtWidgets.QLabel(self.layoutWidget)
        self.label_DMDCalibrationImageRatio.setObjectName("label_DMDCalibrationImageRatio")
        self.horizontalLayout_3.addWidget(self.label_DMDCalibrationImageRatio)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btn_Calibrate = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_Calibrate.setObjectName("btn_Calibrate")
        self.horizontalLayout_4.addWidget(self.btn_Calibrate)
        self.cbox_CalibrateCheck = QtWidgets.QCheckBox(self.layoutWidget)
        self.cbox_CalibrateCheck.setObjectName("cbox_CalibrateCheck")
        self.horizontalLayout_4.addWidget(self.cbox_CalibrateCheck)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 780, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad_Calibration = QtWidgets.QAction(MainWindow)
        self.actionLoad_Calibration.setObjectName("actionLoad_Calibration")
        self.actionSave_Calibration = QtWidgets.QAction(MainWindow)
        self.actionSave_Calibration.setObjectName("actionSave_Calibration")
        self.menuFile.addAction(self.actionLoad_Calibration)
        self.menuFile.addAction(self.actionSave_Calibration)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tab_MaskFunctionality.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DMD Mask App"))
        self.label_DMDCalibrationMaskRatio.setText(_translate("MainWindow", "Calibration Mask Ratio"))
        self.tab_MaskFunctionality.setTabText(self.tab_MaskFunctionality.indexOf(self.Calibration), _translate("MainWindow", "Calibration"))
        self.label_ThresholdLevel.setText(_translate("MainWindow", "Threshold Level"))
        self.tab_MaskFunctionality.setTabText(self.tab_MaskFunctionality.indexOf(self.Threshold), _translate("MainWindow", "Threshold"))
        self.label_NumberOfSlits.setText(_translate("MainWindow", "Number of Slits"))
        self.label_SlitWidth.setText(_translate("MainWindow", "Slit Width (um)"))
        self.label_SlitSeparation.setText(_translate("MainWindow", "Slit Separation (um)"))
        self.tab_MaskFunctionality.setTabText(self.tab_MaskFunctionality.indexOf(self.Slit), _translate("MainWindow", "Slit"))
        self.label_NumberOfPinholes.setText(_translate("MainWindow", "Number of Pinholes"))
        self.label_PinholeRadius.setText(_translate("MainWindow", "Pinhole Radius (um)"))
        self.label_PinholePitch.setText(_translate("MainWindow", "Pinhole Pitch (um)"))
        self.tab_MaskFunctionality.setTabText(self.tab_MaskFunctionality.indexOf(self.Pinhole), _translate("MainWindow", "Pinhole"))
        self.label_DMDSizeXMaskGen.setText(_translate("MainWindow", "DMD Size X"))
        self.label_DMDSizeYMaskGen.setText(_translate("MainWindow", "DMD Size Y"))
        self.btn_DMDMaskGen.setText(_translate("MainWindow", "Generate DMD Mask"))
        self.btn_DMDMaskSave.setText(_translate("MainWindow", "Save Current Mask"))
        self.btn_CamImageImport.setText(_translate("MainWindow", "Import Camera Image"))
        self.label_DMDSizeX.setText(_translate("MainWindow", "DMD Size X"))
        self.label_DMDSizeY.setText(_translate("MainWindow", "DMD Size Y"))
        self.label_DMDCalibrationImageRatio.setText(_translate("MainWindow", "Calibration Image Ratio"))
        self.btn_Calibrate.setText(_translate("MainWindow", "Calibrate"))
        self.cbox_CalibrateCheck.setText(_translate("MainWindow", "Lock Calibration?"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionLoad_Calibration.setText(_translate("MainWindow", "Load Calibration"))
        self.actionSave_Calibration.setText(_translate("MainWindow", "Save Calibration"))
